// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pds.Data.Context;

#nullable disable

namespace Pds.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260817215722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pds.Domain.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AnonymizedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("anonymized_at")
                        .HasComment("Quando a identificacao foi removida. A partir daqui nenhuma linha da conta guarda dado pessoal.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name")
                        .HasComment("Nome da conta, exibido no painel.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<DateTime?>("PurgeAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("purge_at")
                        .HasComment("Data em que a exclusao vira definitiva. Gravada no pedido para sobreviver a mudanca de politica.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_accounts_deleted_at");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_public_id");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasComment("Conta: a fronteira de isolamento do sistema. Todo dado pertence a uma, e nenhuma consulta atravessa de uma para outra.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id")
                        .HasComment("Conta dona do projeto. E por este campo que o isolamento filtra.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name")
                        .HasComment("Nome do projeto, unico dentro da conta entre os que nao foram apagados.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasComment("active | archived. Arquivado continua visivel, so para de aceitar coisa nova.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_projects_deleted_at");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_public_id");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_account_id_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasComment("Projeto: a unidade que o cliente configura e a que identifica de onde veio cada relato.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hash")
                        .HasComment("So para a secreta: o valor original nunca e guardado.");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_used_at")
                        .HasComment("Ultimo uso, em UTC. Ajuda a saber se da para revogar sem quebrar nada.");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("prefix")
                        .HasComment("Primeiros caracteres, para identificar a chave na lista sem revela-la.");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id")
                        .HasComment("Projeto dono da chave.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("revoked_at")
                        .HasComment("Nulo enquanto valida; preenchido ao regenerar, em UTC. Nao confundir com deleted_at.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type")
                        .HasComment("public | secret. Define se o valor e guardado em claro ou como hash.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.Property<string>("Value")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("value")
                        .HasComment("So para a publica: vai aparecer no site do cliente, entao fica em claro.");

                    b.HasKey("Id")
                        .HasName("pk_project_keys");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_project_keys_deleted_at");

                    b.HasIndex("Hash")
                        .HasDatabaseName("ix_project_keys_hash");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_keys_public_id");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_project_keys_value");

                    b.HasIndex("ProjectId", "Type")
                        .HasDatabaseName("ix_project_keys_project_id_type");

                    b.ToTable("project_keys", null, t =>
                        {
                            t.HasComment("Chave que liga o sistema do cliente ao nosso. Tabela separada de projects porque chave e rotacionada e revogada, e guardar quando cada uma valeu e o que permite investigar um incidente depois.");

                            t.HasCheckConstraint("ck_project_keys_value_xor_hash", "(type = 'public' AND value IS NOT NULL AND hash IS NULL) OR (type = 'secret' AND value IS NULL AND hash IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id")
                        .HasComment("Conta a que este usuario pertence.");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url")
                        .HasComment("Foto vinda do Google. Opcional.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email")
                        .HasComment("E-mail vindo do Google. Pode mudar la, entao serve para contato e nao como identidade.");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_subject")
                        .HasComment("O sub do Google. Identificador estavel: e por ele que o login reconhece a pessoa.");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login_at")
                        .HasComment("Ultimo acesso, em UTC.");

                    b.Property<string>("Name")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name")
                        .HasComment("Nome vindo do Google.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_users_account_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_users_deleted_at");

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasDatabaseName("ux_users_google_subject")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_public_id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("Quem entra no painel. A identidade vem do Google, entao nao ha senha nem recuperacao.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.Project", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Account", "Account")
                        .WithMany("Projects")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectKey", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Project", "Project")
                        .WithMany("Keys")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_keys_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Pds.Domain.Entities.User", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Account", "Account")
                        .WithMany("Users")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Pds.Domain.Entities.Account", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Pds.Domain.Entities.Project", b =>
                {
                    b.Navigation("Keys");
                });
#pragma warning restore 612, 618
        }
    }
}
