// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pds.Data.Context;

#nullable disable

namespace Pds.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260919002433_AddReportPublicStageDueAt")]
    partial class AddReportPublicStageDueAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pds.Domain.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AnonymizedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("anonymized_at")
                        .HasComment("Quando a identificacao foi removida. A partir daqui nenhuma linha da conta guarda dado pessoal.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name")
                        .HasComment("Nome da conta, exibido no painel.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<DateTime?>("PurgeAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("purge_at")
                        .HasComment("Data em que a exclusao vira definitiva. Gravada no pedido para sobreviver a mudanca de politica.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_accounts_deleted_at");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_public_id");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasComment("Conta: a fronteira de isolamento do sistema. Todo dado pertence a uma, e nenhuma consulta atravessa de uma para outra.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id")
                        .HasComment("Conta de origem. Continua apontando para ela depois de anonimizada.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Quando a linha foi gravada, em UTC. Difere de occurred_at quando houve retentativa.");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("occurred_at")
                        .HasComment("Quando aconteceu, em UTC. E esta a data que a analise usa.");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload")
                        .HasComment("O resto do evento em chave e valor, para tipo novo entrar sem migracao.");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id")
                        .HasComment("Projeto de origem. Anulavel porque o projeto some de verdade e o evento fica.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio.");

                    b.Property<long?>("ReportId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_id")
                        .HasComment("Relato a que o evento se refere. Nulo quando o evento nao nasce de um relato.");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source")
                        .HasComment("widget | panel | api | public_page. De onde a acao partiu.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type")
                        .HasComment("report_created | report_viewed por enquanto. A lista cresce conforme o produto anda.");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasComment("Quem do time fez. Nulo quando a acao veio de fora, e nos eventos anteriores a esta coluna.");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_events_public_id");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_events_report_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_events_user_id");

                    b.HasIndex("AccountId", "OccurredAt")
                        .HasDatabaseName("ix_events_account_id_occurred_at");

                    b.HasIndex("ProjectId", "OccurredAt")
                        .HasDatabaseName("ix_events_project_id_occurred_at");

                    b.ToTable("events", null, t =>
                        {
                            t.HasComment("O registro do que aconteceu, e a tabela que responde a pergunta de pesquisa. Unica do sistema que so cresce: nunca e alterada e nunca e apagada, nem quando a conta que a originou e excluida.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id")
                        .HasComment("Conta dona do projeto. E por este campo que o isolamento filtra.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<int>("MappingVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mapping_version")
                        .HasComment("Versao do mapeamento que vale agora. Zero enquanto nada foi ligado. Nao e o maior valor de project_status_mappings: desfazer tudo grava uma versao sem linha nenhuma.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name")
                        .HasComment("Nome do projeto, unico dentro da conta entre os que nao foram apagados.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasComment("active | archived. Arquivado continua visivel, so para de aceitar coisa nova.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_projects_deleted_at");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_public_id");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_account_id_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasComment("Projeto: a unidade que o cliente configura e a que identifica de onde veio cada relato.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectCycleSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AcceptsQuestionsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("accepts_questions_default")
                        .HasComment("Como a opcao de aceitar duvidas vem marcada no formulario. A escolha final e de quem relata, nao do projeto.");

                    b.Property<bool>("AllowsReopen")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_reopen")
                        .HasComment("Se quem relatou pode reabrir.");

                    b.Property<string>("ClosureTrigger")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("closure_trigger")
                        .HasComment("last_column | button — se o relato encerra ao cair na ultima coluna ativa ou por um botao proprio.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<int>("InfoRequestCloseDays")
                        .HasColumnType("integer")
                        .HasColumnName("info_request_close_days")
                        .HasComment("Dias depois do aviso ate encerrar como sem retorno. Encerrado assim continua reabrivel.");

                    b.Property<bool>("InfoRequestEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("info_request_enabled")
                        .HasComment("Se o time pode devolver o relato pedindo informacao em vez de encerrar.");

                    b.Property<int>("InfoRequestWarnDays")
                        .HasColumnType("integer")
                        .HasColumnName("info_request_warn_days")
                        .HasComment("Dias sem resposta ate avisar quem relatou de que o relato vai encerrar.");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id")
                        .HasComment("Projeto dono da configuracao. Unico entre os nao apagados, e e o que faz o 1:1.");

                    b.Property<int>("PublicDelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("public_delay_minutes")
                        .HasComment("Quanto o lado publico espera antes de mudar. Zero e o comportamento anterior a esta etapa; acima de zero e a janela para desfazer um movimento errado.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<bool>("ReopenRequiresComment")
                        .HasColumnType("boolean")
                        .HasColumnName("reopen_requires_comment")
                        .HasComment("Se reabrir exige dizer por que. O motivo e para quem vai pegar o relato de volta.");

                    b.Property<long?>("ReopenStateId")
                        .HasColumnType("bigint")
                        .HasColumnName("reopen_state_id")
                        .HasComment("Para qual coluna interna o relato volta ao ser reaberto. Nula usa a primeira ativa.");

                    b.Property<bool>("SatisfactionEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("satisfaction_enabled")
                        .HasComment("Se a nota e pedida ao confirmar.");

                    b.Property<bool>("SatisfactionRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("satisfaction_required")
                        .HasComment("Se confirmar exige responder. Mesmo exigindo, 'prefiro nao responder' continua existindo, fora da escala.");

                    b.Property<string>("SatisfactionStyle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("satisfaction_style")
                        .HasComment("stars | number — como a escala de 1 a 5 aparece. Muda o desenho, e nao o dado: os dois guardam o mesmo inteiro.");

                    b.Property<bool>("TrackingCodeCanAct")
                        .HasColumnType("boolean")
                        .HasColumnName("tracking_code_can_act")
                        .HasComment("Se o protocolo sozinho confirma e reabre, ou se as duas acoes exigem o link. Ler e inofensivo; reabrir mexe na fila do time.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.HasKey("Id")
                        .HasName("pk_project_cycle_settings");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_project_cycle_settings_deleted_at");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_cycle_settings_project_id")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_cycle_settings_public_id");

                    b.HasIndex("ReopenStateId")
                        .HasDatabaseName("ix_project_cycle_settings_reopen_state_id");

                    b.ToTable("project_cycle_settings", null, t =>
                        {
                            t.HasComment("Como o ciclo fecha neste projeto: quando encerra, quanto espera antes de quem relatou ver, se da para reabrir e como, e o que a pessoa responde no fim. Uma linha por projeto, criada so quando alguem salva — os padroes vivem no codigo, e projeto sem linha e projeto que nunca precisou mudar nada.");

                            t.HasCheckConstraint("ck_project_cycle_settings_info_request_days", "info_request_warn_days >= 1 AND info_request_warn_days <= 365 AND info_request_close_days >= 1 AND info_request_close_days <= 365");

                            t.HasCheckConstraint("ck_project_cycle_settings_public_delay", "public_delay_minutes >= 0 AND public_delay_minutes <= 10080");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectInitialState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id")
                        .HasComment("Projeto a que esta escolha pertence.");

                    b.Property<long>("ProjectStateId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_state_id")
                        .HasComment("Estado onde o relato deste tipo cai. Do mesmo projeto, e ativo.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("report_type")
                        .HasComment("bug, improvement ou question. Unico por projeto entre os nao apagados.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.HasKey("Id")
                        .HasName("pk_project_initial_states");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_project_initial_states_deleted_at");

                    b.HasIndex("ProjectStateId")
                        .HasDatabaseName("ix_project_initial_states_project_state_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_initial_states_public_id");

                    b.HasIndex("ProjectId", "ReportType")
                        .IsUnique()
                        .HasDatabaseName("ux_project_initial_states_project_id_report_type")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("project_initial_states", null, t =>
                        {
                            t.HasComment("Onde um relato cai ao entrar, por tipo. E tabela em vez de colunas em projects para tipo novo nao pedir migracao, e a linha so nasce quando o cliente escolhe: sem linha, vale o primeiro estado ativo da fila.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hash")
                        .HasComment("So para a secreta: o valor original nunca e guardado.");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_used_at")
                        .HasComment("Ultimo uso, em UTC. Ajuda a saber se da para revogar sem quebrar nada.");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("prefix")
                        .HasComment("Primeiros caracteres, para identificar a chave na lista sem revela-la.");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id")
                        .HasComment("Projeto dono da chave.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("revoked_at")
                        .HasComment("Nulo enquanto valida; preenchido ao regenerar, em UTC. Nao confundir com deleted_at.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type")
                        .HasComment("public | secret. Define se o valor e guardado em claro ou como hash.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.Property<string>("Value")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("value")
                        .HasComment("So para a publica: vai aparecer no site do cliente, entao fica em claro.");

                    b.HasKey("Id")
                        .HasName("pk_project_keys");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_project_keys_deleted_at");

                    b.HasIndex("Hash")
                        .HasDatabaseName("ix_project_keys_hash");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_keys_public_id");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_project_keys_value");

                    b.HasIndex("ProjectId", "Type")
                        .HasDatabaseName("ix_project_keys_project_id_type");

                    b.ToTable("project_keys", null, t =>
                        {
                            t.HasComment("Chave que liga o sistema do cliente ao nosso. Tabela separada de projects porque chave e rotacionada e revogada, e guardar quando cada uma valeu e o que permite investigar um incidente depois.");

                            t.HasCheckConstraint("ck_project_keys_value_xor_hash", "(type = 'public' AND value IS NOT NULL AND hash IS NULL) OR (type = 'secret' AND value IS NULL AND hash IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectOrigin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowsSubdomains")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allows_subdomains")
                        .HasComment("Quando verdadeiro vale para app.site.com e loja.site.com sem precisar de uma linha para cada.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("domain")
                        .HasComment("Dominio autorizado, guardado em minusculo, sem esquema e sem barra final. A porta faz parte quando informada.");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id")
                        .HasComment("Projeto que autoriza este dominio.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.HasKey("Id")
                        .HasName("pk_project_origins");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_project_origins_deleted_at");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_origins_project_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_origins_public_id");

                    b.HasIndex("ProjectId", "Domain")
                        .IsUnique()
                        .HasDatabaseName("ux_project_origins_project_id_domain")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("project_origins", null, t =>
                        {
                            t.HasComment("De quais enderecos um relato pode ser aberto. A chave publica viaja no site do cliente e qualquer um consegue le-la; sem esta lista, a chave copiada de um site funciona em qualquer outro.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectPublicStage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowsReturn")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_return")
                        .HasComment("A jornada pode voltar para esta etapa. Por padrao ela nao anda para tras, e esta marca e a excecao combinada.");

                    b.Property<bool>("AwaitsReporter")
                        .HasColumnType("boolean")
                        .HasColumnName("awaits_reporter")
                        .HasComment("A etapa espera quem relatou, e nao o time. Ainda nao e lida por ninguem: nasce com a tabela para nao custar migracao depois.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("description")
                        .HasComment("A frase que explica o passo. Obrigatoria: rotulo sozinho e o que a ferramenta de dentro ja dava.");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_terminal")
                        .HasComment("A etapa em que o trabalho do time acaba. Nao quer dizer encerrado: a confirmacao de quem relatou vem depois dela.");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("label")
                        .HasComment("O nome do passo, como quem relatou le. Unico no projeto: dois rotulos iguais na mesma linha do tempo nao teriam como ser distinguidos.");

                    b.Property<string>("NextStep")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("next_step")
                        .HasComment("O que vem depois, quando o cliente quer dizer. Nulo na ultima etapa, que nao tem depois.");

                    b.Property<string>("Outcome")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome")
                        .HasComment("done | wont_do | no_answer | duplicate. Nulo fora da etapa terminal, obrigatorio nela: fim sem desfecho e fim sem explicacao.");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position")
                        .HasComment("Ordem da jornada. Nao e unica: reordenar reescreve a lista inteira de uma vez.");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id")
                        .HasComment("Projeto dono da etapa. A jornada e de cada sistema, nao da conta.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.HasKey("Id")
                        .HasName("pk_project_public_stages");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_project_public_stages_deleted_at");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_public_stages_project_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_public_stages_public_id");

                    b.HasIndex("ProjectId", "Label")
                        .IsUnique()
                        .HasDatabaseName("ux_project_public_stages_project_id_label")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("project_public_stages", null, t =>
                        {
                            t.HasComment("A jornada que quem relatou acompanha. Separada de project_states porque o time precisa de detalhe que quem esta de fora nao precisa: varios estados caem numa etapa so, e essa perda de detalhe e o produto.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("Nulo enquanto o estado aceita relato novo; preenchido para aposenta-lo sem apagar, porque relato antigo continua apontando para ele.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name")
                        .HasComment("Nome dado pelo time, como Analise ou Corrigindo. Renomear nao reescreve o passado: o evento guarda o nome que valia na epoca.");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position")
                        .HasComment("Ordem na tela, escolhida pelo cliente. Fila de trabalho tem sequencia, entao nao serve a ordem alfabetica.");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id")
                        .HasComment("Projeto dono do estado. A fila de trabalho e de cada sistema, nao da conta.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.HasKey("Id")
                        .HasName("pk_project_states");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_project_states_deleted_at");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_states_project_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_states_public_id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_project_states_project_id_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("project_states", null, t =>
                        {
                            t.HasComment("A fila de trabalho de cada projeto, com os nomes que o proprio cliente deu. Existe porque estados fixos, definidos por nos, obrigariam todo time a descrever o processo dele com as nossas palavras.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectStatusMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id")
                        .HasComment("Projeto dono. Repetido aqui porque toda consulta comeca por projeto e versao.");

                    b.Property<long>("ProjectPublicStageId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_public_stage_id")
                        .HasComment("A etapa de fora, onde quem relatou passa a ver o relato.");

                    b.Property<long>("ProjectStateId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_state_id")
                        .HasComment("O estado de dentro, de onde o relato sai.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version")
                        .HasComment("A versao a que esta linha pertence. A que vale agora e projects.mapping_version.");

                    b.HasKey("Id")
                        .HasName("pk_project_status_mappings");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_project_status_mappings_deleted_at");

                    b.HasIndex("ProjectPublicStageId")
                        .HasDatabaseName("ix_project_status_mappings_project_public_stage_id");

                    b.HasIndex("ProjectStateId")
                        .HasDatabaseName("ix_project_status_mappings_project_state_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_status_mappings_public_id");

                    b.HasIndex("ProjectId", "Version")
                        .HasDatabaseName("ix_project_status_mappings_project_id_version");

                    b.HasIndex("ProjectId", "Version", "ProjectStateId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_status_mappings_project_id_version_project_state_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("project_status_mappings", null, t =>
                        {
                            t.HasComment("Liga N estados de dentro a 1 etapa de fora. Versionada: alterar grava o conjunto inteiro de novo, um numero acima, porque reescrever o mapa apagaria o sentido de tudo que ja aconteceu.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectWidgetSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccentColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("accent_color")
                        .HasComment("Cor do gatilho em #rrggbb. Nulo quer dizer o acento do proprio produto, que acompanha o tema.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<string>("DefaultReportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_report_type")
                        .HasComment("bug | improvement | question. Vem pre-marcado, e e o tipo gravado quando o seletor esta escondido.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled")
                        .HasComment("Desliga a ferramenta no site inteiro sem ninguem editar o HTML do cliente.");

                    b.Property<string>("LauncherLabel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("launcher_label")
                        .HasComment("O texto dentro do gatilho, o botao que fica parado na pagina.");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("placeholder")
                        .HasComment("O texto cinza da caixa vazia. E ele que faz a pergunta certa.");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("position")
                        .HasComment("bottom_right | bottom_left. De que canto inferior a ferramenta sai.");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id")
                        .HasComment("Projeto a que esta configuracao pertence.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<bool>("ShowsTypeField")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("shows_type_field")
                        .HasComment("Mostra ou esconde o seletor de tipo no formulario.");

                    b.Property<string>("SuccessMessage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("success_message")
                        .HasComment("A frase acima do protocolo, na confirmacao.");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("theme")
                        .HasComment("auto | light | dark. Auto segue o sistema de quem visita o site do cliente.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("title")
                        .HasComment("O titulo dentro do quadro. Nunca o nome do projeto, que e nome interno.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.HasKey("Id")
                        .HasName("pk_project_widget_settings");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_project_widget_settings_deleted_at");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_widget_settings_project_id")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_widget_settings_public_id");

                    b.ToTable("project_widget_settings", null, t =>
                        {
                            t.HasComment("Como a ferramenta de relato aparece no site de um projeto. Uma linha por projeto, criada so quando alguem salva: os padroes vivem no codigo, e projeto sem linha e projeto que nunca precisou mudar nada.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.Report", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("AcceptsQuestions")
                        .HasColumnType("boolean")
                        .HasColumnName("accepts_questions")
                        .HasComment("Quem relatou aceita responder duvidas da equipe. Escolha dela, nao do projeto. Nulo e o relato que entrou antes de a pergunta existir: ninguem perguntou, e ninguem respondeu.");

                    b.Property<string>("AccessTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("access_token_hash")
                        .HasComment("Hash do token do link de acompanhamento. O valor original so existe na URL entregue.");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id")
                        .HasComment("Conta dona do relato, repetido de proposito em vez de chegar pelo projeto.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<string>("Origin")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("origin")
                        .HasComment("Dominio informado pela pagina que embutiu a ferramenta. Indicio, nunca prova.");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id")
                        .HasComment("Projeto de onde o relato veio, resolvido pela chave publica da requisicao.");

                    b.Property<long?>("ProjectPublicStageId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_public_stage_id")
                        .HasComment("Em que etapa da jornada publica o relato aparece. Nulo enquanto ele nao apareceu em nenhuma. E cache, como project_state_id: a verdade e a sequencia de eventos.");

                    b.Property<long?>("ProjectStateId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_state_id")
                        .HasComment("Onde o relato esta na fila do projeto. Nulo quando o projeto ainda nao tem estado nenhum. E cache: a verdade e a sequencia de eventos.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<DateTime?>("PublicStageDueAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("public_stage_due_at")
                        .HasComment("Quando a ultima mudanca de etapa publica passa a valer para quem relatou. Preenchida e a janela para desfazer; nula e o estado normal. E ela que sobrevive, e nao a mensagem na fila.");

                    b.Property<string>("Route")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("route")
                        .HasComment("So o caminho da pagina, sem query e sem fragmento: e na query que viaja dado sensivel.");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("text")
                        .HasComment("O relato como a pessoa escreveu.");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tracking_code")
                        .HasComment("O protocolo que a pessoa le e repete. Alfabeto sem 0, O, 1 e I; colisao tratada na geracao.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type")
                        .HasComment("bug | improvement | question. Lista fixa por enquanto.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("AccessTokenHash")
                        .HasDatabaseName("ix_reports_access_token_hash");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_reports_deleted_at");

                    b.HasIndex("ProjectPublicStageId")
                        .HasDatabaseName("ix_reports_project_public_stage_id");

                    b.HasIndex("ProjectStateId")
                        .HasDatabaseName("ix_reports_project_state_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_reports_public_id");

                    b.HasIndex("PublicStageDueAt")
                        .HasDatabaseName("ix_reports_public_stage_due_at")
                        .HasFilter("public_stage_due_at IS NOT NULL");

                    b.HasIndex("TrackingCode")
                        .IsUnique()
                        .HasDatabaseName("ux_reports_tracking_code");

                    b.HasIndex("AccountId", "CreatedAt")
                        .HasDatabaseName("ix_reports_account_id_created_at");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .HasDatabaseName("ix_reports_project_id_created_at");

                    b.ToTable("reports", null, t =>
                        {
                            t.HasComment("O que a pessoa de fora escreveu. Primeira tabela do sistema que nasce sem conta e sem sessao, e por isso carrega o proprio account_id, o protocolo que a pessoa le e o hash do token que abre o acompanhamento.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.ReportClosure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("closed_at")
                        .HasComment("Quando encerrou, em UTC. Separado de created_at porque encerramento agendado e gravado quando a fila o consome.");

                    b.Property<long?>("ClosedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("closed_by_user_id")
                        .HasComment("Quem do time encerrou. Nulo quer dizer que foi o sistema, no fim do prazo do pedido de informacao.");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmed_at")
                        .HasComment("Quando quem relatou confirmou que resolveu. Nulo enquanto nao respondeu.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome")
                        .HasComment("done | wont_do | no_answer | duplicate. Guardado aqui e nao lido da etapa publica: a jornada e configuracao e pode ser reescrita, o desfecho deste relato nao.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason")
                        .HasComment("Por que acabou, escrito por quem encerrou. Obrigatorio: sem ele a pessoa fica sabendo que acabou e nao o que aconteceu.");

                    b.Property<string>("ReopenComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reopen_comment")
                        .HasComment("Por que reabriu, quando o projeto pede o comentario. E para quem for pegar o trabalho de novo, e nao para justificar o pedido.");

                    b.Property<DateTime?>("ReopenedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reopened_at")
                        .HasComment("Quando quem relatou reabriu. Preenchido, esta linha deixou de ser o fim do relato.");

                    b.Property<long>("ReportId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_id")
                        .HasComment("Relato encerrado.");

                    b.Property<int?>("Satisfaction")
                        .HasColumnType("integer")
                        .HasColumnName("satisfaction")
                        .HasComment("Nota de 1 a 5 dada na confirmacao. Nula quando nao houve resposta, e nula tambem quando houve recusa — que e outra coisa, e mora na coluna ao lado.");

                    b.Property<bool>("SatisfactionDeclined")
                        .HasColumnType("boolean")
                        .HasColumnName("satisfaction_declined")
                        .HasComment("A pessoa clicou em 'prefiro nao responder'. Fora da escala de proposito: dentro dela viraria a nota mais baixa e a media contaria recusa como insatisfacao.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.HasKey("Id")
                        .HasName("pk_report_closures");

                    b.HasIndex("ClosedByUserId")
                        .HasDatabaseName("ix_report_closures_closed_by_user_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_report_closures_deleted_at");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_report_closures_public_id");

                    b.HasIndex("ReportId", "ClosedAt")
                        .HasDatabaseName("ix_report_closures_report_id_closed_at");

                    b.ToTable("report_closures", null, t =>
                        {
                            t.HasComment("O fim de um relato, com o motivo, e a resposta de quem o escreveu. Tabela propria e nao comentario: acontece uma vez por fechamento, carrega um desfecho e espera resposta. Uma linha por fechamento — relato reaberto e fechado de novo ganha linha nova, e as duas ficam.");

                            t.HasCheckConstraint("ck_report_closures_satisfaction_range", "satisfaction IS NULL OR (satisfaction >= 1 AND satisfaction <= 5)");

                            t.HasCheckConstraint("ck_report_closures_satisfaction_xor_declined", "NOT (satisfaction IS NOT NULL AND satisfaction_declined)");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.ReportContext", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("key")
                        .HasComment("Nome do dado em ingles e snake_case, como user_agent ou viewport_width.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<long>("ReportId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_id")
                        .HasComment("Relato a que este dado pertence.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.Property<string>("Value")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value")
                        .HasComment("O valor como chegou, sempre texto. A interpretacao fica com quem le.");

                    b.HasKey("Id")
                        .HasName("pk_report_contexts");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_report_contexts_deleted_at");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_report_contexts_public_id");

                    b.HasIndex("ReportId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_report_contexts_report_id_key")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("report_contexts", null, t =>
                        {
                            t.HasComment("O que veio junto com o relato sem ninguem digitar. Tabela separada em vez de colunas em reports porque o que se vai querer saber amanha ainda nao esta decidido hoje.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.ReportInternalComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("body")
                        .HasComment("O texto como o time escreveu. Nao sai desta tabela, nem para o payload do evento.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<long>("ReportId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_id")
                        .HasComment("Relato comentado.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasComment("Quem escreveu. Obrigatorio: comentario interno sem autor nao serve para decidir nada depois.");

                    b.HasKey("Id")
                        .HasName("pk_report_internal_comments");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_report_internal_comments_deleted_at");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_report_internal_comments_public_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_report_internal_comments_user_id");

                    b.HasIndex("ReportId", "CreatedAt")
                        .HasDatabaseName("ix_report_internal_comments_report_id_created_at");

                    b.ToTable("report_internal_comments", null, t =>
                        {
                            t.HasComment("O que o time escreve entre si. E tabela separada do comentario publico, e nao um campo de visibilidade, porque com sinalizador basta esquecer um filtro para vazar e com tabelas separadas vazar exige uma consulta que nao existe.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.ReportPublicComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("body")
                        .HasComment("O texto que vai ser lido por quem relatou.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<long>("ReportId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_id")
                        .HasComment("Relato comentado.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasComment("Quem escreveu, do lado de dentro. A camada publica nao mostra o nome, mas quem respondeu e pergunta interna.");

                    b.HasKey("Id")
                        .HasName("pk_report_public_comments");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_report_public_comments_deleted_at");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_report_public_comments_public_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_report_public_comments_user_id");

                    b.HasIndex("ReportId", "CreatedAt")
                        .HasDatabaseName("ix_report_public_comments_report_id_created_at");

                    b.ToTable("report_public_comments", null, t =>
                        {
                            t.HasComment("O que o time escolhe dizer a quem relatou. Ainda nao tem leitor: a camada que o relator le vem depois, e ate la ele e publico no nome. Tabela separada do interno pelo mesmo motivo que a outra.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Chave interna, sequencial. Nunca sai da aplicacao.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id")
                        .HasComment("Conta a que este usuario pertence.");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url")
                        .HasComment("Foto vinda do Google. Opcional.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Criacao do registro, em UTC.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Nulo enquanto o registro vale; preenchido no lugar de apagar.");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email")
                        .HasComment("E-mail vindo do Google. Pode mudar la, entao serve para contato e nao como identidade.");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_subject")
                        .HasComment("O sub do Google. Identificador estavel: e por ele que o login reconhece a pessoa.");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login_at")
                        .HasComment("Ultimo acesso, em UTC.");

                    b.Property<string>("Name")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name")
                        .HasComment("Nome vindo do Google.");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasComment("Identificador publico, GUID aleatorio. E o que aparece em URL e API.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Ultima alteracao, em UTC.");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_users_account_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_users_deleted_at");

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasDatabaseName("ux_users_google_subject")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_public_id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("Quem entra no painel. A identidade vem do Google, entao nao ha senha nem recuperacao.");
                        });
                });

            modelBuilder.Entity("Pds.Domain.Entities.Event", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_events_accounts_account_id");

                    b.HasOne("Pds.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_events_projects_project_id");

                    b.HasOne("Pds.Domain.Entities.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_events_reports_report_id");

                    b.HasOne("Pds.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_events_users_user_id");

                    b.Navigation("Account");

                    b.Navigation("Project");

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pds.Domain.Entities.Project", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Account", "Account")
                        .WithMany("Projects")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectCycleSettings", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_cycle_settings_projects_project_id");

                    b.HasOne("Pds.Domain.Entities.ProjectState", "ReopenState")
                        .WithMany()
                        .HasForeignKey("ReopenStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_project_cycle_settings_project_states_reopen_state_id");

                    b.Navigation("Project");

                    b.Navigation("ReopenState");
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectInitialState", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_initial_states_projects_project_id");

                    b.HasOne("Pds.Domain.Entities.ProjectState", "ProjectState")
                        .WithMany()
                        .HasForeignKey("ProjectStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_initial_states_project_states_project_state_id");

                    b.Navigation("Project");

                    b.Navigation("ProjectState");
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectKey", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Project", "Project")
                        .WithMany("Keys")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_keys_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectOrigin", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Project", "Project")
                        .WithMany("Origins")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_origins_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectPublicStage", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_public_stages_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectState", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_states_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectStatusMapping", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_status_mappings_projects_project_id");

                    b.HasOne("Pds.Domain.Entities.ProjectPublicStage", "ProjectPublicStage")
                        .WithMany()
                        .HasForeignKey("ProjectPublicStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_status_mappings_project_public_stage_id");

                    b.HasOne("Pds.Domain.Entities.ProjectState", "ProjectState")
                        .WithMany()
                        .HasForeignKey("ProjectStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_status_mappings_project_states_project_state_id");

                    b.Navigation("Project");

                    b.Navigation("ProjectPublicStage");

                    b.Navigation("ProjectState");
                });

            modelBuilder.Entity("Pds.Domain.Entities.ProjectWidgetSettings", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_widget_settings_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Pds.Domain.Entities.Report", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_accounts_account_id");

                    b.HasOne("Pds.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_projects_project_id");

                    b.HasOne("Pds.Domain.Entities.ProjectPublicStage", "ProjectPublicStage")
                        .WithMany()
                        .HasForeignKey("ProjectPublicStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reports_project_public_stages_project_public_stage_id");

                    b.HasOne("Pds.Domain.Entities.ProjectState", "ProjectState")
                        .WithMany()
                        .HasForeignKey("ProjectStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reports_project_states_project_state_id");

                    b.Navigation("Account");

                    b.Navigation("Project");

                    b.Navigation("ProjectPublicStage");

                    b.Navigation("ProjectState");
                });

            modelBuilder.Entity("Pds.Domain.Entities.ReportClosure", b =>
                {
                    b.HasOne("Pds.Domain.Entities.User", "ClosedByUser")
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_report_closures_users_closed_by_user_id");

                    b.HasOne("Pds.Domain.Entities.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_closures_reports_report_id");

                    b.Navigation("ClosedByUser");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Pds.Domain.Entities.ReportContext", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Report", "Report")
                        .WithMany("Contexts")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_contexts_reports_report_id");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Pds.Domain.Entities.ReportInternalComment", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_internal_comments_reports_report_id");

                    b.HasOne("Pds.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_internal_comments_users_user_id");

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pds.Domain.Entities.ReportPublicComment", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_public_comments_reports_report_id");

                    b.HasOne("Pds.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_public_comments_users_user_id");

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pds.Domain.Entities.User", b =>
                {
                    b.HasOne("Pds.Domain.Entities.Account", "Account")
                        .WithMany("Users")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Pds.Domain.Entities.Account", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Pds.Domain.Entities.Project", b =>
                {
                    b.Navigation("Keys");

                    b.Navigation("Origins");
                });

            modelBuilder.Entity("Pds.Domain.Entities.Report", b =>
                {
                    b.Navigation("Contexts");
                });
#pragma warning restore 612, 618
        }
    }
}
